### ISSUE TITLE
Transformer模型报错

### ISSUE THREAD

**Issue by bitsk** [PaddlePaddle/PaddleTS#112]
W0915 12:02:58.731670  1250 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W0915 12:02:58.744315  1250 gpu_resources.cc:91] device: 0, cuDNN Version: 8.5.
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    model.fit(train_dataset, val_dataset)
  File "/usr/local/lib/python3.8/dist-packages/paddlets/models/dl/paddlepaddle/paddle_base_impl.py", line 321, in fit
    self._fit(train_dataloader, valid_dataloaders)
  File "/usr/local/lib/python3.8/dist-packages/paddlets/models/dl/paddlepaddle/paddle_base_impl.py", line 347, in _fit
    self._train_epoch(train_dataloader)
  File "/usr/local/lib/python3.8/dist-packages/paddlets/models/dl/paddlepaddle/paddle_base_impl.py", line 415, in _train_epoch
    batch_logs = self._train_batch(X, y)
  File "/usr/local/lib/python3.8/dist-packages/paddlets/models/dl/paddlepaddle/paddle_base_impl.py", line 434, in _train_batch
    output = self._network(X)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlets/models/dl/paddlepaddle/transformer.py", line 196, in forward
    out = self._transformer(src, tgt)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 1628, in forward
    memory = self.encoder(src, src_mask=src_mask)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 971, in forward
    src_mask = _convert_attention_mask(src_mask, src.dtype,
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 108, in _convert_attention_mask
    mha_meta = _prepare_mha_meta(attn_mask, enable_cudnn)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 134, in _prepare_mha_meta
    assert attn_mask is not None, \
AssertionError: The attention mask should be given for MultiHeadAttention  when enable_cudnn=True. But received attn_mask = None

**Comment by willionZS** [comment]
看起来是attn_mask这个参数为None的情况造成的？

**Comment by Annnnnnnnnnnnn** [comment]
能提供一下paddle的版本么，最好可以提供一份可以复现的代码最小集合。
