### ISSUE TITLE
使用backtest时报错

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/PaddleTS#232]
代码如下：
from paddlets.utils import backtest

q_loss, quantiles = backtest(data=ts_test_scaled,
                             model=deepar,
                             start="2021/9/24 19:00",
                             metric=QuantileLoss([0.1, 0.5, 0.9]),
                             predict_window=30**6,
                             stride=30**6,
                             return_predicts=True
                             )

quantiles.plot(
    add_data=ts_test_scaled,
    low_quantile=0.05,
    high_quantile=0.95
)
plt.show()
报错如下：
[2022-11-07 16:10:23,106] [paddlets.models.common.callbacks.callbacks] [INFO] Best weights from best epoch are automatically used!
[2022-11-07 16:10:23,119] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,155] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,207] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,217] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,227] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,241] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,262] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,280] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:23,300] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,822] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,822] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,822] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,823] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,823] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,823] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,823] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,823] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,885] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,905] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,908] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,934] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,948] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,954] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,956] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,956] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,963] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,963] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,964] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,964] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,968] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:31,968] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,000] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,004] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,034] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,080] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,084] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,120] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,123] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,142] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,159] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:32,180] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,758] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,758] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,758] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,758] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,758] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,759] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,759] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,759] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,817] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,821] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,844] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,861] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,911] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,913] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,917] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:34,935] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,653] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,653] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,653] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,653] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,654] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,654] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,654] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,654] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,736] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,748] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,754] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,756] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,795] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,797] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,814] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:35,831] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,401] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,401] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,401] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,401] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,401] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,402] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,402] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,402] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,437] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,464] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,501] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,504] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,538] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,541] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,560] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:36,578] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,085] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,085] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,085] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,085] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,085] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,086] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,086] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,086] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,133] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,167] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,184] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,190] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,241] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,245] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,248] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,264] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,746] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,746] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,746] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,746] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,747] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,747] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,747] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,747] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,788] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,828] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,846] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,863] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,871] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,887] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,907] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:37,923] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,344] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,344] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,344] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,344] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,344] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,345] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,345] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,345] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,387] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,423] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,430] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,447] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,467] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,499] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,503] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:38,521] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,035] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,035] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,035] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,035] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,035] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,036] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,036] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,036] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,086] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,123] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,137] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,139] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,139] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,142] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,144] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,145] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,146] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,146] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,147] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,148] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,168] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,199] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,217] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,221] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,244] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,286] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,306] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,311] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,327] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,347] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,367] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:39,383] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\automl\searcher.py:4: DeprecationWarning: The module `ray.tune.suggest` has been moved to `ray.tune.search` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest` with `ray.tune.search`.
  from ray.tune.suggest import BasicVariantGenerator
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\automl\searcher.py:5: DeprecationWarning: The module `ray.tune.suggest.optuna` has been moved to `ray.tune.search.optuna` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest.optuna` with `ray.tune.search.optuna`.
  from ray.tune.suggest.optuna import OptunaSearch
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\flaml\tune\__init__.py:5: DeprecationWarning: The module `ray.tune.sample` has been moved to `ray.tune.search.sample` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.sample` with `ray.tune.search.sample`.
  from ray.tune import (
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\flaml\tune\space.py:6: DeprecationWarning: The module `ray.tune.suggest.variant_generator` has been moved to `ray.tune.search.variant_generator` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest.variant_generator` with `ray.tune.search.variant_generator`.
  from ray.tune.suggest.variant_generator import generate_variants
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\automl\searcher.py:6: DeprecationWarning: The module `ray.tune.suggest.flaml` has been moved to `ray.tune.search.flaml` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest.flaml` with `ray.tune.search.flaml`.
  from ray.tune.suggest.flaml import CFO
C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\automl\searcher.py:8: DeprecationWarning: The module `ray.tune.suggest.bohb` has been moved to `ray.tune.search.bohb` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest.bohb` with `ray.tune.search.bohb`.
  from ray.tune.suggest.bohb import TuneBOHB
Backtest Progress:   0%|          | 0/9 [00:00<?, ?it/s]C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddle\fluid\layers\tensor.py:657: UserWarning: paddle.assign doesn't support float64 input now due to current platform protobuf data limitation, we convert it to float32
  warnings.warn(
Backtest Progress:   0%|          | 0/9 [00:01<?, ?it/s]
[2022-11-07 16:10:57,802] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,802] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,803] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,843] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,867] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,902] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,904] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,953] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,959] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,962] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-11-07 16:10:57,983] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Paddle-release-2.2/PaddleTS/demos/fit_deepar_model.py", line 46, in <module>
    q_loss, quantiles = backtest(data=ts_test_scaled,
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\utils\backtest.py", line 150, in backtest
    score_dict = metric(real, predict)
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\metrics\base.py", line 262, in __call__
    res_array = self._build_prob_metrics_data(tsdataset_true, tsdataset_pred, self._TYPE)
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\metrics\base.py", line 104, in _build_prob_metrics_data
    target_true, target_pred = self._reindex_data(target_true, target_pred)
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\paddlets\metrics\base.py", line 197, in _reindex_data
    merge_index = pd.merge(target_true.time_index.to_frame(index=False), target_pred.time_index.to_frame(index=False))
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\pandas\core\reshape\merge.py", line 106, in merge
    op = _MergeOperation(
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\pandas\core\reshape\merge.py", line 681, in __init__
    self._validate_specification()
  File "C:\ProgramData\Anaconda3\envs\paddlets\lib\site-packages\pandas\core\reshape\merge.py", line 1346, in _validate_specification
    raise MergeError(
pandas.errors.MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

**Comment by QGN123** [comment]
辛苦提供上游模型相关代码，目前仅根据backtest代码无法复现您的问题

**Comment by QGN123** [comment]
[依然无法复现您的问题，你打印看下您训练的数据的time_index，和backtest数据的time_index名称是否相等？
![c6128a7b93c43078dc97a2a08](https://user-images.githubusercontent.com/38217558/200277936-d8284709-1a75-432d-b65a-0de5a8f8be09.png)

**Comment by jiangxinufo** [comment]
![1667817260824](https://user-images.githubusercontent.com/53360080/200289298-9abf6408-3ea6-40fa-961c-07aa5350a2d5.png)

**Comment by QGN123** [comment]
问题已定位，原数据index的有name，预测出来的数据index没有name，在旧版本没有问题，在新版本metric更新后会导致问题。

**Comment by QGN123** [comment]
已沟通临时解决方案，此问题会在PaddleTS下一个小版本发布后修复

**Comment by jiangxinufo** [comment]
感谢PaddleTS国宁同学帮忙解决问题，很棒

**Comment by QGN123** [comment]
fixed in https://github.com/PaddlePaddle/PaddleTS/pull/240
