### ISSUE TITLE
autots 模型测试阶段发生报错

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/PaddleTS#250]
ImportError: cannot import name 'hparams' from 'tensorboardX.summary' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tensorboardX/summary.py)

`import pandas as pd
import os

import shutil
from paddlets.models.forecasting import MLPRegressor
from paddlets.automl.autots import AutoTS
# 通过pandas读取数据并显示前三条，与上图一一对应
# csv_path = "tu_share_data_day/688388.SH.csv"
tu_share_data_day = os.listdir("tu_share_data_day")
for one in tu_share_data_day:
    csv_path = os.path.join("tu_share_data_day", one)

    dam_data = pd.read_csv(csv_path).values.tolist()
    if len(dam_data) < 100:
        continue
    dam_data.reverse()
    for i in range(len(dam_data) - 1):
        dam_data[i].append(dam_data[i + 1][4])
        dam_data[i].append(dam_data[i + 1][5])

        dam_data[i].append(dam_data[i + 1][6])
        dam_data[i].append(int(i + 1))
    # print(dam_data)
    dam_data = pd.DataFrame(dam_data[:-1],
                            columns=['ts_code', 'trade_date', 'open', 'high', 'low', 'close',
                                     'pre_close', 'change', 'pct_chg', 'vol', 'amount', 'next_high',
                                     'next_low',
                                     'next_close', 'index_new'])
    from paddlets.datasets import TSDataset

    # 构建数据集
    dataset = TSDataset.load_from_dataframe(
        dam_data,  # pd.DataFrame
        time_col="index_new",  # 索引
        target_cols=['next_high', 'next_low',
                     'next_close'],  # 需要预测的结果
        observed_cov_cols=['open', 'high', 'low', 'close',
                           'pre_close', 'change', 'pct_chg', 'vol', 'amount']  # 观测协变量
    )
    # 划分训练集和验证集
    train_dataset, val_dataset = dataset.split(0.8)  # 8:2
    
    autots_model = AutoTS(MLPRegressor, 96, 2)
    autots_model.fit(train_dataset, val_dataset)`

**Comment by natureLanguageQing** [comment]
`(pid=17430) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/automl/searcher.py:4: DeprecationWarning: The module `ray.tune.suggest` has been moved to `ray.tune.search` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest` with `ray.tune.search`.`

**Comment by natureLanguageQing** [comment]
‘’‘Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 1475, in stop_trial
    iteration=self._iteration, trials=self._trials, trial=trial
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ray/tune/callback.py", line 333, in on_trial_complete
    callback.on_trial_complete(**info)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ray/tune/logger/logger.py", line 150, in on_trial_complete
    self.log_trial_end(trial, failed=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ray/tune/logger/tensorboardx.py", line 241, in log_trial_end
    self._try_log_hparams(trial, scrubbed_result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ray/tune/logger/tensorboardx.py", line 273, in _try_log_hparams
    from tensorboardX.summary import hparams
ImportError: cannot import name 'hparams' from 'tensorboardX.summary' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tensorboardX/summary.py)’‘’

**Comment by natureLanguageQing** [comment]
已经解决 是ray的安装问题导致的 `pip install -U ray ray[tune] ray[defaults] optuna
`
