### ISSUE TITLE
import paddlets报错

### ISSUE THREAD

**Issue by newne** [PaddlePaddle/PaddleTS#251]
系统版本：Ubuntu 22.04
电脑配置： i7-12700 + Nvidia RTX 3070
在conda环境中安装正常，import时报错
```
(pdts) ncg@ncg-pc:~$ pip list | grep paddlets
paddlets           1.0.1
(pdts) ncg@ncg-pc:~$ pip list | grep paddlepaddle
paddlepaddle-gpu   2.3.2.post111
(pdts) ncg@ncg-pc:~$ python
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddlets import TSDataset
Error: Can not import avx core while this file exists: /home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/__init__.py", line 5, in <module>
    from paddlets.pipeline import Pipeline
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/pipeline/__init__.py", line 4, in <module>
    from paddlets.pipeline.pipeline import Pipeline
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/pipeline/pipeline.py", line 16, in <module>
    from paddlets.utils.utils import get_tsdataset_max_len, split_dataset
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/utils/__init__.py", line 8, in <module>
    from paddlets.utils.backtest import backtest
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/utils/backtest.py", line 12, in <module>
    from paddlets.metrics import Metric, MSE
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/metrics/__init__.py", line 7, in <module>
    from paddlets.metrics.metrics import (
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddlets/metrics/metrics.py", line 8, in <module>
    import paddle
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/ncg/anaconda3/envs/pdts/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

**Comment by QGN123** [comment]
refer to https://github.com/PaddlePaddle/Paddle/issues/44571, glibc >= 2.34 时会有这个问题，Paddle团队正在解决。

**Comment by QGN123** [comment]
可以升级paddlepaddle到最新的2.4.0版本试下，我看有人说2.4.0解决了这个问题~

**Comment by newne** [comment]
@QGN123 感谢，问题已解决

```
Successfully installed paddlepaddle-gpu-2.4.0rc0
(pdts) ncg@ncg-pc:~$ python
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlets
>>> 
```
