### ISSUE TITLE
AutoTS.fit()遇到的相关问题

### ISSUE THREAD

**Issue by sly111** [PaddlePaddle/PaddleTS#263]
去运行时提示这些未能完成
Traceback (most recent call last):
  File "/Users/susheng/PycharmProjects/paddleTest/AutoTS.py", line 124, in <module>
    autots_tcn.fit(ts_train, ts_val)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/logger/logger.py", line 27, in wrapper
    result = f(*args, **kwargs)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/automl/autots.py", line 207, in fit
    analysis = self._optimize_runner.optimize(self._estimator,
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/automl/optimize_runner.py", line 204, in optimize
    return tune.run(run_trial, num_samples=n_trials, config=running_search_space,
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/ray/tune/tune.py", line 771, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [run_trial_732b269c, run_trial_88119474, run_trial_7c009fba, run_trial_94cc868a, run_trial_ab0a0170, run_trial_a7e53298, run_trial_afbec2c2, run_trial_be90113e])

然后我去看快ray-result对应trail的报错文档，发现他们基本显示的
Failure # 1 (occurred at 2022-11-17_19-39-14)
[36mray::ImplicitFunc.train()[39m (pid=30278, ip=127.0.0.1, repr=run_trial)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 325, in entrypoint
    return self._trainable_func(
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 651, in _trainable_func
    output = fn()
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/automl/optimize_runner.py", line 174, in run_trial
    score = fit_and_score(train_data=train_tsdataset,
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/utils/validation.py", line 127, in fit_and_score
    estimator.fit(train_data, valid_data)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/models/forecasting/dl/paddle_base_impl.py", line 346, in fit
    self._fit(train_dataloader, valid_dataloaders)
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/models/forecasting/dl/paddle_base_impl.py", line 363, in _fit
    self._network = self._init_network()
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/models/forecasting/dl/tcn.py", line 341, in _init_network
    return _TCNModule(
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/models/forecasting/dl/tcn.py", line 126, in __init__
    raise_if_not(
  File "/Users/susheng/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlets/logger/logger.py", line 135, in raise_if_not
    raise ValueError(message)
ValueError: The valid range of `kernel_size` is (1, in_chunk_len], got kernel_size:1 <= 1 or kernel_size:1 > in_chunk_len:24.

看起来像kernel-size不合规导致的，请问这该如何修改呢？

**Comment by sly111** [comment]
使用的模型是TCNRegressor，但之前使用的TransformerModel也有一样的错误，构建模型部分代码部分也只指定了窗口大小
`autots_tcn=AutoTS(TCNRegressor, 24, 6)
autots_tcn.fit(ts_train, ts_val)`

**Comment by LinWencong** [comment]
感谢你的反馈，这个错误在 tcn 模型版本更新之后发生（增加了kernel_size更加严格的限制）；
请升级至 paddlets 的1.0.2或者后续的更高版本，已经解决了这个问题；
