### ISSUE TITLE
TFT model can't be saved 

### ISSUE THREAD

**Issue by ruige123456** [PaddlePaddle/PaddleTS#346]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlets\models\forecasting\dl\paddle_base.py", line 233, in save
    pickle.dump(self, f)
TypeError: cannot pickle 'Tensor' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\py\dossen-alg-api\paddle_tft.py", line 220, in <module>
    main()
  File "D:\work\py\dossen-alg-api\paddle_tft.py", line 198, in main
    model = train(train_dataset, valid_dataset)
  File "D:\work\py\dossen-alg-api\paddle_tft.py", line 162, in train
    model.save(RNN_MODEL_PATH)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlets\models\forecasting\dl\paddle_base.py", line 235, in save
    raise_log(ValueError("error occurred while saving %s, err: %s" % (abs_model_path, str(e))))
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlets\logger\logger.py", line 112, in raise_log
    raise exception
ValueError: error occurred while saving D:\work\py\dossen-alg-api\model\tft\tft_model, err: cannot pickle 'Tensor' object

**Comment by kehuo** [comment]
感谢反馈，会看下这个问题。

**Comment by kehuo** [comment]
fixed @ [PR#355](https://github.com/PaddlePaddle/PaddleTS/pull/355)
