### ISSUE TITLE
使用AnomalyTransformer训练时序异常检测模型时出现问题。

### ISSUE THREAD

**Issue by Hoogck** [PaddlePaddle/PaddleTS#360]
1.环境：centos7  paddlepaddle-gpu==2.3.2  paddlets== 1.1.0  cuda11.2  nvidia-driver460.39  

2.问题描述：
   使用paddlets自带数据NAB_TEMP训练时序异常检测模型报错
   其中AutoEncoder、VAE训练正常，使用AnomalyTransformer训练报错，错误信息提示输入中有NaN值：
W0130 16:10:13.515244 53384 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W0130 16:10:13.518093 53384 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[2023-01-30 16:10:14,805] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 000| loss: 0.000000| val_0_mse: 0.000000| 0:00:01s
[2023-01-30 16:10:15,530] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 001| loss: -0.041732| val_0_mse: 0.000000| 0:00:01s
[2023-01-30 16:10:16,260] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 002| loss: -0.039907| val_0_mse: 0.000000| 0:00:02s
[2023-01-30 16:10:17,004] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 003| loss: -0.040051| val_0_mse: 0.000000| 0:00:03s
[2023-01-30 16:10:17,789] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 004| loss: -0.043504| val_0_mse: 0.000000| 0:00:04s
[2023-01-30 16:10:18,632] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 005| loss: -0.042415| val_0_mse: 0.000000| 0:00:05s
[2023-01-30 16:10:19,405] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 006| loss: -0.039770| val_0_mse: 0.000000| 0:00:05s
[2023-01-30 16:10:20,047] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 007| loss: -0.040144| val_0_mse: 0.000000| 0:00:06s
[2023-01-30 16:10:20,691] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 008| loss: -0.040011| val_0_mse: 0.000000| 0:00:07s
[2023-01-30 16:10:21,333] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 009| loss: -0.040603| val_0_mse: 0.000000| 0:00:07s
[2023-01-30 16:10:22,034] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 010| loss: -0.047260| val_0_mse: 0.000000| 0:00:08s
[2023-01-30 16:10:22,037] [paddlets.models.common.callbacks.callbacks] [INFO] 
Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_mse = 0.000000
[2023-01-30 16:10:22,037] [paddlets.models.common.callbacks.callbacks] [INFO] Best weights from best epoch are automatically used!
[2023-01-30 16:10:22,589] [paddlets.metrics.base] [WARNING] Tsdataset true's and pred's time_index do not match, the result will be calculated according to the intersection!
model:AutoEncoder f1:  0.049204052098408106
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:25,481] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 000| loss: 29.800358| val_0_mse: 0.311698| 0:00:02s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:27,665] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 001| loss: 24.403154| val_0_mse: 0.311698| 0:00:05s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:29,726] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 002| loss: 35.839511| val_0_mse: 0.673310| 0:00:07s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:31,828] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 003| loss: 31.323491| val_0_mse: 0.311699| 0:00:09s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:34,021] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 004| loss: 17.868246| val_0_mse: 0.311697| 0:00:11s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:36,139] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 005| loss: 52.115227| val_0_mse: 0.311697| 0:00:13s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:38,255] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 006| loss: 56.577546| val_0_mse: 0.311697| 0:00:15s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:40,470] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 007| loss: 52.143328| val_0_mse: 0.311698| 0:00:17s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:42,456] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 008| loss: 58.133194| val_0_mse: 0.311698| 0:00:19s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:44,506] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 009| loss: 56.605193| val_0_mse: 0.671903| 0:00:21s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:46,533] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 010| loss: 54.171396| val_0_mse: 0.311697| 0:00:23s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:48,609] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 011| loss: 65.563436| val_0_mse: 0.311698| 0:00:25s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:50,706] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 012| loss: 53.648452| val_0_mse: 0.311698| 0:00:28s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:52,738] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 013| loss: 49.160785| val_0_mse: 0.311697| 0:00:30s
/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[2023-01-30 16:10:54,891] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 014| loss: 59.601553| val_0_mse: 0.311698| 0:00:32s
[2023-01-30 16:10:54,906] [paddlets.models.common.callbacks.callbacks] [INFO] 
Early stopping occurred at epoch 14 with best_epoch = 4 and best_val_0_mse = 0.311697
[2023-01-30 16:10:54,906] [paddlets.models.common.callbacks.callbacks] [INFO] Best weights from best epoch are automatically used!
[2023-01-30 16:10:56,156] [paddlets.metrics.base] [WARNING] Tsdataset true's and pred's time_index do not match, the result will be calculated according to the intersection!
model:VAE f1:  0.2502206531332745
[2023-01-30 16:11:09,499] [paddlets.models.anomaly.dl.utils] [INFO] epoch: 0, Updating learning rate to 0.0002
[2023-01-30 16:11:13,823] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 000| loss: 505.360534| val_0_mse: 0.311697| 0:00:17s
[2023-01-30 16:11:26,160] [paddlets.models.anomaly.dl.utils] [INFO] epoch: 1, Updating learning rate to 0.0001
[2023-01-30 16:11:30,438] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 001| loss: 2401649.044474| val_0_mse: 0.321708| 0:00:34s
[2023-01-30 16:11:42,506] [paddlets.models.anomaly.dl.utils] [INFO] epoch: 2, Updating learning rate to 5e-05
[2023-01-30 16:11:47,047] [paddlets.models.common.callbacks.callbacks] [INFO] epoch 002| loss: 10089118.069477| val_0_mse: 0.575549| 0:00:50s
[2023-01-30 16:11:58,801] [paddlets.models.anomaly.dl.utils] [INFO] epoch: 3, Updating learning rate to 2.5e-05
Traceback (most recent call last):
  File "anomaly_detect.py", line 48, in <module>
    model.fit(train_tsdata_scaled,val_tsdata_scaled)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/models/anomaly/dl/anomaly_transformer.py", line 406, in fit
    self._fit(train_dataloader, valid_dataloaders)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/models/anomaly/dl/anomaly_transformer.py", line 435, in _fit
    self._predict_epoch(eval_name, valid_dataloader)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/models/anomaly/dl/anomaly_base.py", line 593, in _predict_epoch
    metrics_logs = self._metric_container_dict[name](y_pred, y_true)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/metrics/metrics.py", line 395, in __call__
    res = metric.metric_fn(y_true, y_score)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/metrics/utils.py", line 42, in wrapper
    return func(obj, y_true, y_score, **kwargs)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/paddlets/metrics/metrics.py", line 55, in metric_fn
    return metrics.mean_squared_error(y_true, y_score)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 439, in mean_squared_error
    y_true, y_pred, multioutput
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 96, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/****/toolkit/anaconda3/envs/fx/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

3.训练代码如下：
import os
import paddle
import numpy as np
from paddlets.models.anomaly import AutoEncoder,AnomalyTransformer,VAE,USAD,MTADGAT
from paddlets.datasets.tsdataset import TSDataset
from paddlets.datasets.repository import get_dataset
from paddlets.utils.utils import plot_anoms
from paddlets.metrics import F1,ACC,Precision,Recall
from paddlets.transform  import Fill,StandardScaler
from paddlets.metrics import MAE,MSE,QuantileLoss
from paddlets.transform import TimeFeatureGenerator
os.environ['CUDA_VISIBLE_DEVICES']="1"

ts_data = get_dataset('NAB_TEMP') # label_col: 'label', feature_cols: 'value'
#ts_data =  TSDataset.load_from_csv(csv_file,time_col="timestamp",label_col="label",feature_cols="value",freq="5min")

#fill  nan
fill =  Fill(cols=["label","value"],method="pre")
ts_data = fill.transform_one(ts_data)

#time_f = TimeFeatureGenerator(["month", "weekday", "hour", "dayofyear", "weekofyear"])
#ts_gen = time_f.fit_transform(ts_data)
#ts_data = TSDataset.concat([ts_data,ts_gen])

print(f"#####The input ts_data.target:{ts_data.target}")
print(f"#####The input ts_data.known_cov:{ts_data.known_cov}")
print(f"#####The input ts_data.observed_cov:{ts_data.observed_cov}")

#plot_anoms(origin_data=ts_data, feature_name='value')

#set seed
seed = 2022
paddle.seed(seed)
np.random.seed(seed)
train_tsdata, val_test_tsdata = ts_data.split(0.3)
val_tsdata, test_tsdata = val_test_tsdata.split(0.5)

#standardize
scaler = StandardScaler("value")
scaler.fit(train_tsdata)
train_tsdata_scaled = scaler.transform(train_tsdata)
val_tsdata_scaled = scaler.transform(val_tsdata)
test_tsdata_scaled = scaler.transform(test_tsdata)

model_list = {"AutoEncoder":AutoEncoder,"VAE":VAE,"AnomalyTransformer":AnomalyTransformer}
for name,model in model_list.items():
	model = model(in_chunk_len=10, max_epochs=50)
	model.fit(train_tsdata_scaled,val_tsdata_scaled)
	
	pred_label = model.predict(test_tsdata_scaled)
	lable_name = pred_label.target.data.columns[0]
	
	f1 = F1()(test_tsdata, pred_label)
	precision = Precision()(test_tsdata, pred_label)
	recall = Recall()(test_tsdata, pred_label)
	print(f'model:{name} f1: ', f1[lable_name])
	print(f'model:{name} precision: ', precision[lable_name])
	print(f'model:{name} recall: ', recall[lable_name])
	
	#plot_anoms(origin_data=test_tsdata, predict_data=pred_label, feature_name="value")
	
	#pred_score = model.predict_score(test_data_scaled)
    #plot_anoms(origin_data=test_tsdata, predict_data=pred_score, feature_name="value").figure.savefig(f"{name}_predict_result.png")

**Comment by willionZS** [comment]
非常感谢，该问题已经修复~
