### ISSUE TITLE
官方文档中Paddle Inference Support样例报错RuntimeError

### ISSUE THREAD

**Issue by Husky1999** [PaddlePaddle/PaddleTS#388]
RuntimeError: (Unavailable) LoadCombine operator fails to open file ./rnn.pdiparams, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:55)
  [operator < load_combine > error]

使用版本：
paddle: 2.4.1
paddlets: 1.1.0

**Comment by Husky1999** [comment]
`
from paddlets.datasets.repository import get_dataset
from paddlets.models.forecasting.dl.rnn import RNNBlockRegressor
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

# prepare data
dataset = get_dataset("WTH")

rnn = RNNBlockRegressor(
    in_chunk_len=4,
    out_chunk_len=2,
    max_epochs=10
)

#fit
rnn.fit(dataset)

#predict
rnn.predict(dataset)

rnn.save("./rnn", network_model=True, dygraph_to_static=True)

import paddle.inference as paddle_infer
config = paddle_infer.Config("./rnn.pdmodel", "./rnn.pdiparams")
predictor = paddle_infer.create_predictor(config)
input_names = predictor.get_input_names()
print(f"input_name: f{input_names}")

import json
with open("./rnn_model_meta") as f:
    json_data = json.load(f)
    print(json_data)
from paddlets.utils.utils import build_ts_infer_input

input_data = build_ts_infer_input(dataset, "./rnn_model_meta")

for key, value in json_data['input_data'].items():
    input_handle1 = predictor.get_input_handle(key)
    #set batch_size=1
    value[0] = 1
    input_handle1.reshape(value)
    input_handle1.copy_from_cpu(input_data[key])

predictor.run()
output_names = predictor.get_output_names()
output_handle = predictor.get_output_handle(output_names[0])
output_data = output_handle.copy_to_cpu()
print(output_data)`


报错：
Traceback (most recent call last):
  File "D:/work/------/rnn_z.py", line 26, in <module>
    predictor = paddle_infer.create_predictor(config)
RuntimeError: (Unavailable) LoadCombine operator fails to open file ./rnn.pdiparams, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/load_combine_op.h:53)
  [operator < load_combine > error]

**Comment by Husky1999** [comment]
`
from paddlets.datasets.repository import get_dataset
from paddlets.models.forecasting.dl.rnn import RNNBlockRegressor
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

# prepare data
dataset = get_dataset("WTH")

rnn = RNNBlockRegressor(
    in_chunk_len=4,
    out_chunk_len=2,
    max_epochs=10
)

#fit
rnn.fit(dataset)

#predict
rnn.predict(dataset)

rnn.save("./rnn", network_model=True, dygraph_to_static=True)

import paddle.inference as paddle_infer
config = paddle_infer.Config("./rnn.pdmodel", "./rnn.pdiparams")
predictor = paddle_infer.create_predictor(config)
input_names = predictor.get_input_names()
print(f"input_name: f{input_names}")

import json
with open("./rnn_model_meta") as f:
    json_data = json.load(f)
    print(json_data)
from paddlets.utils.utils import build_ts_infer_input

input_data = build_ts_infer_input(dataset, "./rnn_model_meta")

for key, value in json_data['input_data'].items():
    input_handle1 = predictor.get_input_handle(key)
    #set batch_size=1
    value[0] = 1
    input_handle1.reshape(value)
    input_handle1.copy_from_cpu(input_data[key])

predictor.run()
output_names = predictor.get_output_names()
output_handle = predictor.get_output_handle(output_names[0])
output_data = output_handle.copy_to_cpu()
print(output_data)`

报错：
`Traceback (most recent call last):
  File "D:/work/-------/rnn_z.py", line 26, in <module>
    predictor = paddle_infer.create_predictor(config)
RuntimeError: (Unavailable) LoadCombine operator fails to open file ./rnn.pdiparams, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/load_combine_op.h:53)
  [operator < load_combine > error]`

**Comment by Husky1999** [comment]
代码：
```
from paddlets.datasets.repository import get_dataset
from paddlets.models.forecasting.dl.rnn import RNNBlockRegressor
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

# prepare data
dataset = get_dataset("WTH")

rnn = RNNBlockRegressor(
    in_chunk_len=4,
    out_chunk_len=2,
    max_epochs=10
)

#fit
rnn.fit(dataset)

#predict
rnn.predict(dataset)

rnn.save("./rnn", network_model=True, dygraph_to_static=True)

import paddle.inference as paddle_infer
config = paddle_infer.Config("./rnn.pdmodel", "./rnn.pdiparams")
predictor = paddle_infer.create_predictor(config)
input_names = predictor.get_input_names()
print(f"input_name: f{input_names}")

import json
with open("./rnn_model_meta") as f:
    json_data = json.load(f)
    print(json_data)
from paddlets.utils.utils import build_ts_infer_input

input_data = build_ts_infer_input(dataset, "./rnn_model_meta")

for key, value in json_data['input_data'].items():
    input_handle1 = predictor.get_input_handle(key)
    #set batch_size=1
    value[0] = 1
    input_handle1.reshape(value)
    input_handle1.copy_from_cpu(input_data[key])

predictor.run()
output_names = predictor.get_output_names()
output_handle = predictor.get_output_handle(output_names[0])
output_data = output_handle.copy_to_cpu()
print(output_data)
```
报错：
```
Traceback (most recent call last):
  File "D:/work/------/rnn_z.py", line 26, in <module>
    predictor = paddle_infer.create_predictor(config)
RuntimeError: (Unavailable) LoadCombine operator fails to open file ./rnn.pdiparams, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/load_combine_op.h:53)
  [operator < load_combine > error]
```
