### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

### ISSUE THREAD

**Issue by ahbon123** [PaddlePaddle/PaddleTS#395]
Hello,
I get the following error when extracting data from paddlets, what should I do? Thanks.

```
from paddlets.datasets.repository import get_dataset
ts_data = get_dataset('NAB_TEMP') # label_col: 'label', feature_cols: 'value'
```

Out:

```
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Users/x/Documents/tjd/exchange-rate-prediction_2023-05-09/code.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/Documents/tjd/exchange-rate-prediction_2023-05-09/code.py", line 31, in <module>
    from paddlets.datasets.repository import get_dataset
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/__init__.py", line 5, in <module>
    from paddlets.pipeline import Pipeline
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/pipeline/__init__.py", line 4, in <module>
    from paddlets.pipeline.pipeline import Pipeline
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/pipeline/pipeline.py", line 16, in <module>
    from paddlets.utils.utils import get_tsdataset_max_len, split_dataset
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/utils/__init__.py", line 6, in <module>
    from paddlets.utils.utils import get_uuid
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/utils/utils.py", line 18, in <module>
    from paddlets.models.data_adapter import DataAdapter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/models/data_adapter.py", line 4, in <module>
    import paddle
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 52, in <module>
    from . import io
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/io.py", line 31, in <module>
    from paddle.fluid import layers
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/layers/__init__.py", line 29, in <module>
    from . import math_op_patch
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/layers/math_op_patch.py", line 24, in <module>
    from paddle.fluid.dygraph.base import in_declarative_mode
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/dygraph/__init__.py", line 35, in <module>
    from . import checkpoint
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/dygraph/checkpoint.py", line 26, in <module>
    from paddle.fluid.dygraph.jit import _SaveLoadConfig
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 34, in <module>
    from paddle.fluid.dygraph.dygraph_to_static import logging_utils
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/__init__.py", line 32, in <module>
    from . import convert_call_func
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 22, in <module>
    import pdb
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pdb.py", line 77, in <module>
    import code
  File "/Users/x/Documents/tjd/exchange-rate-prediction_2023-05-09/code.py", line 33, in <module>
    ts_data = get_dataset('NAB_TEMP') # label_col: 'label', feature_cols: 'value'
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paddlets/datasets/repository/base.py", line 67, in get_dataset
    df = pd.read_csv(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
```

**Comment by Sunting78** [comment]
using Ubuntu, try the following: 
`sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs`
