### ISSUE TITLE
The time_col can't be the type of numpy.integer, and it must be the type of numpy.datetime64

### ISSUE THREAD

**Issue by yonuyeung** [PaddlePaddle/PaddleTS#457]
指令
`%cd /home/aistudio/PaddleTS-main`
`!python3 train.py --config configs/classification/timesnet_Heartbeat.yaml --task classification --time_feat `

报错
/home/aistudio/PaddleTS-main
/home/aistudio/PaddleTS-main/paddlets/utils/backtest.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import defaultdict, Iterable
[2023-10-21 14:23:29,419] [__main__] [INFO] {'dic': {'batch_size': 16, 'seq_len': 96, 'predict_len': 0, 'label_len': 0, 'do_eval': True, 'epoch': 30, 'training': True, 'eval_metrics': ['acc'], 'dataset': {'name': 'Heartbeat'}, 'model': {'name': 'TimesNetModel', 'model_cfg': {'e_layers': 2, 'num_kernels': 6, 'd_model': 64, 'd_ff': 64, 'top_k': 1, 'window_sampling_limit': None, 'optimizer_params': {'learning_rate': 0.001}}}, 'loss': 'CE', 'test': {'stride': 1}, 'output': 'output/'}}
[2023-10-21 14:24:29,459] [__main__] [INFO] data scale done!
[2023-10-21 14:24:29,459] [__main__] [INFO] generate times feature
[2023-10-21 14:24:29,550] [paddlets] [ERROR] ValueError: The time_col can't be the type of numpy.integer, and it must be the type of numpy.datetime64
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    main(args)
  File "train.py", line 137, in main
    ts_train = time_feature_generator.fit_transform(ts_train)
  File "/home/aistudio/PaddleTS-main/paddlets/transform/base.py", line 180, in fit_transform
    return self.fit(dataset).transform(dataset, inplace)
  File "/home/aistudio/PaddleTS-main/paddlets/transform/base.py", line 112, in transform
    return [self.transform_one(data, inplace) for data in dataset]
  File "/home/aistudio/PaddleTS-main/paddlets/transform/base.py", line 112, in <listcomp>
    return [self.transform_one(data, inplace) for data in dataset]
  File "/home/aistudio/PaddleTS-main/paddlets/logger/logger.py", line 26, in wrapper
    result = f(*args, **kwargs)
  File "/home/aistudio/PaddleTS-main/paddlets/transform/time_feature.py", line 320, in transform_one
    "The time_col can't be the type of numpy.integer, and it must be the type of numpy.datetime64"
  File "/home/aistudio/PaddleTS-main/paddlets/logger/logger.py", line 110, in raise_log
    raise exception
ValueError: The time_col can't be the type of numpy.integer, and it must be the type of numpy.datetime64

**Comment by Sunting78** [comment]
https://aistudio.baidu.com/intro/paddlex 可以直接尝试这里的时序分类模型

**Comment by Sunting78** [comment]
您好，请直接执行`python3 train.py --config configs/classification/timesnet_Heartbeat.yaml --task classification` 去掉time_feat 分类不支持time_feat变量。
