### ISSUE TITLE
3D点云训练报错

### ISSUE THREAD

**Issue by LeeGeong** [PaddlePaddle/PaddleTS#459]
------------------------------------------------
D:\JJH\PaddleX_DeskTop\resources\codelab\lib\site-packages\paddle\io\reader.py:433: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
  warnings.warn(
2023-11-01 12:46:31,104 -  WARNING - No custom op voxelize found, try JIT build
[2023-11-01 12:46:32,062] [    INFO] dist.py:985 - running build
[2023-11-01 12:46:32,063] [    INFO] dist.py:985 - running build_ext
D:\JJH\PaddleX_DeskTop\resources\codelab\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:1438: UserWarning: Failed to check compiler version for cl: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
  warnings.warn(
2023-11-01 12:46:32,192 -     INFO - voxelize builded success!
Traceback (most recent call last):
  File "d:\JJH\Paddle_workspace\7115943\1\run_paddlex.py", line 98, in <module>
    runner.run()
  File "d:\JJH\Paddle_workspace\7115943\1\base\base_run_paddlex.py", line 402, in run
    self.run_train()
  File "d:\JJH\Paddle_workspace\7115943\1\run_paddlex.py", line 50, in run_train
    self.uapi_model.train(
  File "uapi\cv_uapi\paddle3d_uapi\pc_det\model.py", line 102, in uapi.cv_uapi.paddle3d_uapi.pc_det.model.PCDetModel.train
  File "uapi\cv_uapi\paddle3d_uapi\pc_det\model.py", line 104, in uapi.cv_uapi.paddle3d_uapi.pc_det.model.PCDetModel.train
  File "uapi\cv_uapi\paddle3d_uapi\pc_det\model.py", line 115, in uapi.cv_uapi.paddle3d_uapi.pc_det.model.PCDetModel.train
  File "uapi\cv_uapi\paddle3d_uapi\pc_det\runner.py", line 29, in uapi.cv_uapi.paddle3d_uapi.pc_det.runner.PCDetRunner.train
  File "uapi\base\runner.py", line 343, in uapi.base.runner.BaseRunner.run_cmd
uapi.base.utils.errors.CalledProcessError: Command ['D:\\JJH\\PaddleX_DeskTop\\resources\\codelab\\python.exe', 'tools/train.py', '--do_eval', '--config', 'C:\\Users\\Administrator\\.paddle_uapi\\tmpwfncvzbu\\pcdetmodel_CenterPoint_pillars_02voxel.yml', '--batch_size', '4', '--model', 'https://paddle-model-ecology.bj.bcebos.com/uapi/infer_fd/centerpoint_pillars_02voxel/centerpoint_pillars_02voxel_nuscenes_10sweep.pdparams', '--save_dir', 'D:\\JJH\\Paddle_workspace\\7115943\\1\\output'] returned non-zero exit status 3221225477.
PS D:\JJH\Paddle_workspace\7115943\1>

**Comment by Sunting78** [comment]
请到3D套件。
